### ISSUE TITLE
Error when redisplaying form with attachment due to validation errors

### ISSUE THREAD

**Issue by hoenth** [richardvenneman/trestle-active_storage#31] opened 2019-10-30 14:54 UTC
A user will get a 500 error when the following occurs:

1. A form includes an active storage attachment
1. The form is displayed/submitted as part of a new/create action
1. The user included an image/file for the active storage field
1. The associated model has validations and the model fails to save due to a validation
1. The system attempts to redisplay the "new" form (as apposed to edit/update)

The cause of the error is that in the _has_one_field partial, there is a check whether the attachment is attached (`if attachment.attached?`). If this returns true, which would be the case in the above scenario, the attachment preview fields are display, but more importantly, the delete attachment field is also displayed (`<%= builder.check_box("delete_#{field_name}", label: "Delete #{field_name}") %>`). 

The problem is that the delete field is only added to the instance during the :show, :edit, :update, and :destroy actions (line 7 in the controller_concern.rb file). When submitted, you get an `undefined method 'delete_[attachment field name]'`

Is there a specific reason not to add the field during the :create action? I'm happy to issue a PR to add create to the list of actions, or remove the :only constraint.

**Comment by richardvenneman** [comment] 2019-10-31 14:51
Hi @hoenth, thanks for the extensive report and your research!

Unfortunately I haven't had the chance yet to try this plugin with Rails 6 and validations yet.

If I remember correctly, the delete field is not added on the new/create action because the instance is not available yet at that point:

https://github.com/richardvenneman/trestle-active_storage/blob/8ad489f5fdd67596a63debb50563065b11c06fa7/lib/trestle/active_storage/controller_concern.rb#L13

I'm not entirely sure though. I'd be happy to accept a PR if you can fix your specific use case. Otherwise I'll have a look soon.

**Comment by richardvenneman** [comment] 2019-11-06 16:11
@hoenth thanks for your pull request. I'd like to merge it but while reviewing it I tried to reproduce the issue you've described here. I am running a Rails 6 app with active_storage_validations and I'm following your steps, but I can't get the error to be thrown on a new instance form save action.

Could you share a bit more info on your setup or perhaps a minimal reproducible test case?

**Comment by hoenth** [comment] 2019-11-06 16:41
We are running this within a rails 5.2 app. It was not an issue with active storage validation (though i didn't test that specifically), but when there are validations on other fields other than the attachment field and those validations fail. For example, there is a text field (name, perhaps), that is required but is left blank, but the attachment is attached (i.e. profile picture). 

So the create action fails to save the object on which the attachment is attached, and therefor re-renders the :new template. 

I don't think it is related, but we also have a form with multiple sections (tabs), where fields are required on both tabs, and the attachment is on the first tab.

**Comment by richardvenneman** [comment] 2019-11-07 10:56
Thanks for the additional info. Merged your PR and will cut a new version shortly!

**Comment by richardvenneman** [comment] 2019-11-07 10:57
@all-contributors please add @hoenth for bug, code

**Closed by richardvenneman** 2019-11-07 10:56 UTC

**Comment by richardvenneman** [comment] 2019-11-07 11:19
trestle-active_storage 2.2.1 has just been released:

https://rubygems.org/gems/trestle-active_storage/versions/2.2.1
